export const dadosConsulta = [
    {
      dia: "12/8",
      n_urgente: 1,
      p_urgente: 1,
      m_urgente: 1,
      urgente: 1,
      emergencia: 0,
    },
    {
      dia: "13/8",
      n_urgente: 1,
      p_urgente: 1,
      m_urgente: 1,
      urgente: 1,
      emergencia: 1,
    },
    {
      dia: "14/8",
      n_urgente: 1,
      p_urgente: 1,
      m_urgente: 1,
      urgente: 1,
      emergencia: 1,
    },
    {
      dia: "15/8",
      n_urgente: 1,
      p_urgente: 4,
      m_urgente: 1,
      urgente: 1,
      emergencia: 1,
    },
    {
      dia: "16/8",
      n_urgente: 1,
      p_urgente: 4,
      m_urgente: 1,
      urgente: 1,
      emergencia: 1,
    },
    {
      dia: "17/8",
      n_urgente: 1,
      p_urgente: 12,
      m_urgente: 1,
      urgente: 1,
      emergencia: 1,
    },
    {
      dia: "18/8",
      n_urgente: 1,
      p_urgente: 14,
      m_urgente: 1,
      urgente: 1,
      emergencia: 1,
    },
  ];